theme: jekyll-theme-minimal
title: Minimal theme
logo: /logo.jpg
description: Babel fish это бот, который переводит слова и помогает их запоминать https://t.me/babel_fish_bot
show_downloads: false
theme: jekyll-theme-minimal

